// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozeizskxlrdecudqulcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZWl6c2t4bHJkZWN1ZHF1bGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTM0NTcsImV4cCI6MjA2MzY4OTQ1N30.xZOTFdIo0sOhMpGOCM-fv16io2YjDW-jLkrqCFfnjN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);